Fix master compilation by removing chapters
chapter13 causes:

java.lang.IllegalStateException: failed to analyze: java.lang.reflect.InvocationTargetException
...
Caused by: javax.lang.model.type.UnknownTypeException: Unknown type: "none"